devs-in-tech/DevsInTech

- src/components/HeroSection/index.jsx
- src/components/Navbar.jsx
- src/components/button/index.js
> [FIX] : Navbar Improved

- src/components/HeroSection/index.jsx
- src/components/Navbar.jsx
> fix: discord link

- package.json
> fix: pnpm added in engine

- .husky/pre-commit
- .npmrc
- package-lock.json
- package.json
> Allowing npm and pnpm both

- src/pages/index.js
I have updated the index.js file to show the logo of DevsInTech instead of vercel default favicon
> Changed favicon to DevsInTech logo

- src/components/button/index.js
closes #45 
Changed bg color hover on buttons in heros section
> Added hover effect on buttons 

- src/components/HomePage/aboutCommunity/index.jsx
* Fixes the issue - #89 
Resolved the Margin Issues by adding the margin-top on small devices on the home page section.
> Resolved the Margin Issues on the home page

- src/components/ScrollToTop.jsx
- src/pages/home/index.jsx
Closes #82
added a new component back to top button
> feat: add back to top button

- src/components/HeroSection/index.jsx
- src/components/button/index.js
Closes #108
Enhancing design by adding icons to the button
@AbhiPatel10 here what you asked for, made it dynamic
Any kind of feedback would be appreciated.
> Added dynamic icons to the button component

- src/components/Footer.jsx
[[UPDATE] Discord server link is missing #92](https://github.com/devs-in-tech/DevsInTech/issues/92)
> added discord icon to footer

- package.json
- pnpm-lock.yaml
- src/components/HomePage/stats/index.jsx
Closes #126 
Added the counter effect to the numbers in the homepage stats section
> feat: add counter effect

- README.md
Fix : #175
Add correct code of conduct link in README.md file
> Fix Code of conduct link in README.md file

- src/components/HeroSection/index.jsx
> feat: added hero text

- src/components/Navbar.jsx
Closes #160 
Added onClick event to nav list element to close the navigation menu after clicking the link
> BUG :Navigation menu doesn't close after clicking link

- src/components/Navbar.jsx
> feat: make navbar sticky

- src/styles/globals.css
Fixes #159 
Modified scrollbar appearance to match the webpage theme
> style(scrollbar): modified scrollbar appearance

- src/components/FaqAccordion.jsx
- src/components/Navbar.jsx
Added FAQ in navbar with redirecting to FAQ section on home page.
https://github.com/devs-in-tech/DevsInTech/assets/105661636/9098fc6f-0f25-4878-a542-1014487f46b8
> FAQs added in NavBar 

- src/components/Navbar.jsx
- tailwind.config.js
Previously the cards were going on top of the Navbar while hovering . Now it is fixed . 
**Before**
https://github.com/devs-in-tech/DevsInTech/assets/85991449/6aabda9e-2ffc-42c0-9e57-818bd1a84c34
**After**
https://github.com/devs-in-tech/DevsInTech/assets/85991449/ceb6e67d-be48-40b8-a4ed-1e553816b06e
> Fixed : issue #192

- src/components/Footer.jsx
- src/components/HomePage/Events_Cards/index.jsx
- src/components/content/events.js
Closes #178 
- Refactor the card data as per ESLint rule
- Added key attribute in card component
- Fixed the function call in footer
> Improving code quality and removing warning

- src/components/Footer.jsx
Closes #196
I changed the text of the footer section from "lorem Ipsum..." to appropriate text.
> Changed the footer text from "Lorem ipsum ..." to appropriate text.

- src/components/ScrollToTop.jsx
The Go To Top Button Positioning has been changed to solve the issue
> Closes #202 - Go To Top Button Covers Link in Footer

- src/components/FaqAccordion.jsx
- src/components/HomePage/aboutCommunity/index.jsx
Closes #216 
- Added Scroll Margin to About Us and FAQ Section
> Fixed #216

- README.md
> Added badges to ReadMe.md

- src/components/testimonial.js
> "What Our Members Say About Us" section card ui fix

- src/components/content/events.js
Closes #237
Updated with proper data.
> Update data in the events sections

- src/components/ScrollToTop.jsx
- src/pages/events/index.jsx
- src/pages/team/index.jsx
Closes #282
Added Scroll to top button on the team and events page
https://github.com/devs-in-tech/DevsInTech/assets/74114936/919eaae0-6f9e-4980-80d8-a8d41ec0b841
> Added Scroll to top button on the team and events page

- src/components/FaqAccordion.jsx
- src/components/header/index.js
I have added margin and padding to the FAQ section of the website and also checked in mobile mode
. Initially there was very less space between two sections
> feat(frontend): added spacing in FAQ section

- package.json
- pnpm-lock.yaml
- src/pages/home/index.jsx
#133 
close #133
Added the preloader page-
Used hash loader from react spinner library.
> feat: (frontend)Added preloader page using hashloader issue-133

- README.md
- src/components/Footer.jsx
- src/components/HeaderSocialMedia.jsx
Closes #305 
Added linkedin links to footer and header of the website.
Fixed href in readme get in touch section icons.
As you can see the size of the logos got better and now is in a row state, imo looks better but i can change if needed.
> fix: added correct links to linkedin and social media in readme file

- src/pages/events/index.jsx
* Closes #299 
1. Renamed the event card to **Webinars** as suggested.
2. Also updated the description of the card which matches with the updated content.
> Rename Online Tech Events to Webinars

- src/components/testimonial.js
- src/pages/home/index.jsx
Issue Description:
The testimonial.js file is not properly imported in the project, leading to errors and issues when trying to use the testimonial functionality. This issue aims to address the problem and find a solution for the correct import of testimonial.js.
Current Behavior:
Currently, when attempting to import testimonial.js into the project, the import statement is not working as expected. The file is not being recognized, and as a result, the testimonial functionality is not available. This issue prevents the project from utilizing the testimonials feature and may impact the overall user experience.
Expected Behavior:
The testimonial.js file should be successfully imported into the project, allowing the utilization of the testimonial functionality. Importing the file should …
> Fixing Import of testimonial.js

- package.json
- pnpm-lock.yaml
- src/components/Navbar.jsx
- src/pages/Contributors.js
> feat: implement contributors page

- README.md
Closes #329 
Added the website link in the readme file under About Us section.
I have altered in a way that it is easy to navigate and fun to read for new comers.
Do suggest if I need to change the placement of link in the readme file. I placed it here as I found it appropriate after referring to multiple other gssoc projects' readme files.
> docs: website link added in readme

- src/components/HomePage/stats/index.jsx
> Stat responsiveness

- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/style.yml
- **Resolved Errors in feature-request.yml and styles.yml File.**
- **I hope after these changes made working Correctly Now.**
> fix: Resolved Errors in feature-request.yml File and styles.yml File

- src/components/Footer.jsx
1. Removed extra links and added github link to the footer.
> fix: removed extra social media links

- CODE_OF_CONDUCT.md
- next.config.js
- src/components/revealingsoon/index.js
- src/pages/Contributors.js
- src/pages/alan.js
- src/pages/index.js
- src/pages/team/index.jsx
> Replace Teampage to Revealing soon

- src/pages/home/index.jsx
> revert: remove loader

- src/components/HomePage/Events_Cards/card.jsx
- src/pages/events/index.jsx
> fix: event page

- src/pages/Contributors.js
> fix: contributor page
